from handlers.picture import picture_router
from handlers.shop import shop_router
from handlers.start import start_router
from handlers.myinfo import myinfo_router
from handlers.questions import questions_router
from handlers.products import products_router
from handlers.subscribe import subscribe_router
from handlers.delayed_answer import send_mail
from handlers.group_admin import group_messages_router